# Generated by Django 4.2.5 on 2023-10-18 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collegestoreapp", "0001_initial"),
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Student",
        ),
    ]
